# Generated by Django 3.2.11 on 2022-01-21 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='\n    Contains the Date of the slot.\n    ')),
                ('start_time', models.TimeField(help_text='\n    Contains the start time of the slot.\n    ')),
                ('interval', models.IntegerField(help_text='\n    Contains the interval of the slot.\n    ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='\n    Django auto populates this field whenever a slot is created by a user.\n    ')),
                ('belongs_to', models.ForeignKey(help_text='\n    Stores the user the slot belongs to.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='\n    Contains the email id of the non user booking the slot\n    ', max_length=254)),
                ('name', models.TextField(help_text=' \n    Contains the name of the non user booking the slot\n    ')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='\n    Django automatically populates this field whenever a slot is booked.\n    ')),
                ('slot', models.OneToOneField(help_text='\n    References to the slot that is booked.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='scheduler.calenderslot')),
            ],
        ),
    ]
